"""Description of changes

Revision ID: 253e5399863f
Revises: 9afc27f86625
Create Date: 2024-08-22 08:17:44.294392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253e5399863f'
down_revision = '9afc27f86625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_info')
    # ### end Alembic commands ###
